### ISSUE TITLE
Uncaught ReferenceError: require is not defined at worker.js:1:20 (Code: 10021)

### ISSUE THREAD

**Issue by koliwbr** [edevil/email_worker_parser#1]
Uncaught ReferenceError: require is not defined at worker.js:1:20 (Code: 10021)

**Comment by boynet** [comment]
did you solved it?
I am also getting error from import { EmailMessage } from "cloudflare:email";
```
Uncaught Error: No such module "cloudflare-internal:email".
  imported from "cloudflare:email"  
```

**Comment by koliwbr** [comment]
No

**Comment by boynet** [comment]
so I kinda solve it
change the require to import
and remove all the cloudflare:email stuff

```
import PostalMime from "postal-mime";

async function streamToArrayBuffer(stream, streamSize) {
	let result = new Uint8Array(streamSize);
	let bytesRead = 0;
	const reader = stream.getReader();
	while (true) {
		const { done, value } = await reader.read();
		if (done) {
			break;
		}
		result.set(value, bytesRead);
		bytesRead += value.length;
	}
	return result;
}

export default {
	async fetch(request, env, ctx) {
		return new Response('Hello World!');
	},

	async email(event, env, ctx) {
		const rawEmail = await streamToArrayBuffer(event.raw, event.rawSize);
		const parser = new PostalMime();
		const parsedEmail = await parser.parse(rawEmail);
		console.log("Mail subject: ", parsedEmail.subject);
		console.log("Mail message ID", parsedEmail.messageId);
		console.log("HTML version of Email: ", parsedEmail.html);
		console.log("Text version of Email: ", parsedEmail.text);
		if (parsedEmail.attachments.length == 0) {
			console.log("No attachments");
		} else {
			parsedEmail.attachments.forEach((att) => {
				console.log("Attachment: ", att.filename);
				console.log("Attachment disposition: ", att.disposition);
				console.log("Attachment mime type: ", att.mimeType);
				console.log("Attachment size: ", att.content.byteLength);
			});
		}
		await event.forward(*your email address*);

	},
};

```

now you can use other method if you need to send email but the mail parsing works

**Comment by unilogica** [comment]
Currently not working
<img width="729" alt="Captura de Tela 2024-02-24 às 13 59 55" src="https://github.com/edevil/email_worker_parser/assets/7243084/56e04beb-f008-4d3f-b0f4-f5a08c594f10">

**Comment by xiaopeng12138** [comment]
use wrangler to deploy from local nodejs env to worker, then you can simply `npm install postal-mime`

**Comment by kasteckis** [comment]
Since libraries were out of date and it required more changes that it was mentioned, I recreated the template in case you need it.

https://github.com/kasteckis/cloudflare-email-worker-html-parser
